### ISSUE TITLE
Скомпилированный файл в репозитории

### ISSUE THREAD

**Issue by Relz** [lampeduza1/algorithms-labs#1]
https://github.com/lampeduza1/algorithms-labs/blob/46f6c9d7028d9d13aa8343d4574afe8f281c9e30/task1/main.exe
В репозитории должны быть только исходники. Скомпилированные файлы не могут быть доверенными. Там может быть всё что угодно, в том числе вирусы.

Нужно убрать.

**Comment by lampeduza1** [comment]
удалил
